# AUTOMATICALLY GENERATED by https://github.com/tqdm/shtab
# Usage:
# 1) Copy this to ~/.config/fish/completions/wb-release.fish
# 2) Ensure a binary named wb-release is in your PATH
# See also: https://fishshell.com/docs/current/completions.html#where-to-put-completions


# Parse current commandline:
# - _shtab_wb_cmdpath=(sub)command path seen so far
# - _shtab_wb_npos=number of positional arguments given after it
# - options are skipped based on _shtab_wb_opts_with_value & _shtab_wb_commands lists
function _shtab_wb_scan
  set -g _shtab_wb_cmdpath ''
  set -g _shtab_wb_npos 0
  set -l tokens (commandline -opc)
  set -e tokens[1]
  set -l expect_value 0
  for t in $tokens
    if test $expect_value -eq 1
      set expect_value 0
      continue
    end
    switch "$t"
      case '--*=*'
        continue
      case '-*'
        if contains -- $t $_shtab_wb_opts_with_value
          set expect_value 1
        end
        continue
      case '*'
        if test $_shtab_wb_npos -eq 0
          set -l candidate $t
          if test -n "$_shtab_wb_cmdpath"
            set candidate "$_shtab_wb_cmdpath $t"
          end
          if contains -- $candidate $_shtab_wb_commands
            set -g _shtab_wb_cmdpath $candidate
            continue
          end
        end
        set -g _shtab_wb_npos (math $_shtab_wb_npos + 1)
    end
  end
end

# Condition helper: true if the current (sub)command path equals the given one.
function _shtab_wb_using
  _shtab_wb_scan
  test "$_shtab_wb_cmdpath" = "$argv"
end

set -g _shtab_wb_commands 
set -g _shtab_wb_opts_with_value --log-filename --prefix --target-release -l -t

complete -c wb-release -e
complete -c wb-release -f

complete -c wb-release -n _shtab_wb_using -s h -l help -d 'show this help message and exit'
complete -c wb-release -n _shtab_wb_using -s r -l regenerate -d 'regenerate factory sources.list and exit'
complete -c wb-release -n _shtab_wb_using -s t -l target-release -x -d 'upgrade release to a new target (stable or testing)'
complete -c wb-release -n _shtab_wb_using -s v -l version -d 'print version info and exit'
complete -c wb-release -n _shtab_wb_using -s y -l yes -d 'auto "yes" to all questions'
complete -c wb-release -n _shtab_wb_using -s p -l reset-packages -d 'reset all packages to release versions and exit'
complete -c wb-release -n _shtab_wb_using -s l -l log-filename -x -d 'path to output log file'
complete -c wb-release -n _shtab_wb_using -l no-journald-log -d 'disable journald logging'
complete -c wb-release -n _shtab_wb_using -l reset-url -d 'reset repository URL to default Wirenboard one'
complete -c wb-release -n _shtab_wb_using -l prefix -x -d 'override repository URL prefix'
complete -c wb-release -n _shtab_wb_using -l no-preliminary-update -d 'skip upgrade before switching (not recommended)'

